version: 2

build:
  apt_packages:
    - cmake

python:
  version: "3.7"
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true